# Railway Configuration File for ARC Explainer
# Author: Cascade using Claude 3.7 Sonnet Thinking 

# Build configuration
[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules && npm cache clean --force && npm install --no-optional && npm run build"

# Deployment configuration
[deploy]
startCommand = "npm start"
restartPolicyType = "always"

# Environment variables
[deploy.environment]
NODE_ENV = "production"
NODE_VERSION = "20.13.1"  # Exact Node.js version for consistency

# Nixpacks configuration
[build.nixpacks]
  [build.nixpacks.install]
    # Install dependencies first
    cmds = [
      "npm config set update-notifier false",
      "npm install --no-optional"
    ]

  [build.nixpacks.build]
    # Build the application
    cmds = ["npm run build"]

  [build.nixpacks.start]
    # Start the application
    cmd = "npm start"
