# Railway configuration for ARC Explainer
# Author: CLAUDE 4 Sonnet

# Use Nixpacks (Node.js) for building
[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

# Deployment settings
[deploy]
startCommand = "npm start"
restartPolicyType = "always"

# Environment variables
[deploy.environment]
NODE_ENV = "production"
NODE_VERSION = "20"

# Health check settings
[deploy.healthcheck]
path = "/api/health"
timeout = 10
interval = 30