# Railway Configuration File for ARC Explainer
# Author: Cascade using Claude 3.7 Sonnet Thinking 

# Build configuration
[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

# Deployment configuration
[deploy]
startCommand = "npm start"
restartPolicyType = "always"

# Environment variables
[deploy.environment]
NODE_ENV = "production"
NODE_VERSION = "20"  # Match the Node.js version used in development
