"""
Author: Claude Opus 5
Date: 02-September-2026
PURPOSE: Generate GAMES.md, a one-row-per-game registry of the 50 authored ARC-AGI-3 tasks
in the shape of theredbluepill/arc-interactive's GAMES.md -- id, category, grid, levels,
a one-line description, a preview image and what each action does. The Boss asked for
"something for arc-explainer to consume that looks like that".

WHY GENERATED. Their registry is hand-edited and drifts: their own similarity tooling
exists partly to catch rows that no longer describe their game. Everything in ours already
exists in machine-readable form -- mechanics.json for structure and prose,
frames.json for geometry, frames/ for the picture -- so the table is assembled, not typed,
and re-running this after a batch is the whole maintenance story.

WHAT IS NOT DERIVED. The Category column. Nothing in the digest knows that a game is
"Memory / Hidden State" rather than "Coverage / Path", and guessing it from prose would
produce exactly the vague labels that make their registry hard to skim. It is read from
categories.json, which is human-edited; a game missing from that file is listed as
"Unclassified" rather than given a made-up label.

SRP/DRY check: Pass -- assembly only. Structure comes from mechanic_digest.py, prose from
mechanics-notes.json, pictures from render_authored_frames.py. This computes no new fact
about any game and writes exactly one file.

Run:  python3 scripts/arc3/build_games_registry.py
      python3 scripts/arc3/build_games_registry.py --check   # CI: fail if stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GAMES_DIR = REPO / "server" / "data" / "arc3-games"
OUT = REPO / "docs" / "arc3-games-registry.md"

# What each action id means, per game, in the registry's own shorthand. Derived where the
# digest can tell (a click that reads coordinates vs one that does not); otherwise from the
# note's own controls sentence, which the digest's selftest already cross-checks against
# the actions the source reads.
DPAD = {1, 2, 3, 4}


def action_summary(entry: dict) -> str:
    used = set(entry.get("actionsReferenced") or [])
    bits = []
    if DPAD & used:
        bits.append("• 1-4: Movement")
    if 5 in used:
        bits.append("• 5: Action")
    if entry.get("action6") == "xy-click":
        bits.append("• 6: Click a cell")
    elif entry.get("action6") == "button":
        bits.append("• 6: Button")
    if 7 in used:
        bits.append("• 7: Undo")
    if not bits:
        bits.append("• none read")
    if entry.get("action6Inert"):
        bits.append("• *(offers 6, reads nothing)*")
    return " ".join(bits)


def one_line(note: str) -> str:
    """The registry wants a lead sentence that states the unique rule, not a paragraph."""
    text = " ".join((note or "").split())
    if not text:
        return "—"
    # keep the first two sentences; their rows run about that long
    out, count = [], 0
    for chunk in text.split(". "):
        out.append(chunk)
        count += 1
        if count == 2:
            break
    joined = ". ".join(out).rstrip(".")
    return (joined + ".").replace("|", "\\|")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the file on disk is stale")
    args = ap.parse_args()

    games = json.loads((GAMES_DIR / "mechanics.json").read_text())
    frames_path = GAMES_DIR / "frames.json"
    frames = json.loads(frames_path.read_text()) if frames_path.exists() else {}
    cats_path = GAMES_DIR / "categories.json"
    cats = json.loads(cats_path.read_text()) if cats_path.exists() else {}

    rows = []
    for g in sorted(games, key=lambda g: (cats.get(g["gameId"], "zzz"), g["gameId"])):
        gid = g["gameId"]
        geom = g.get("geometry") or {}
        # Board size, NOT frame size. 15 games do not name their board in a form the digest
        # can read, and frames.json only knows the 64x64 frame -- printing that would say
        # "64x64" for a 12x12 board, which is worse than admitting we do not know.
        if geom.get("N"):
            grid = f"{geom['N']}x{geom['N']}"
        elif geom.get("BOARD"):
            grid = f"{geom['BOARD']}x{geom['BOARD']}"
        else:
            grid = f"?  (cell {geom.get('CELL','?')}px)"
        rows.append(
            f"| {gid} | {cats.get(gid, 'Unclassified')} | {grid} | {g.get('levels') or '?'} "
            f"| {one_line(g.get('mechanic'))} "
            f"| ![{gid}](/api/arc3-mirror/frames/{gid}.png) "
            f"| {action_summary(g)} |"
        )

    unclassified = sum(1 for g in games if g["gameId"] not in cats)
    body = f"""<!-- GENERATED by scripts/arc3/build_games_registry.py -- do not hand-edit.
     Re-run it after a batch; edit categories.json for the one column that is human. -->

# ARC-AGI-3 authored games

The {len(games)} tasks authored in this project, one row each. Structure and geometry are
derived from the game sources by `scripts/arc3/mechanic_digest.py`; the descriptions are
human prose checked against the source; the previews are level 1 as the player first meets
it, rendered by `scripts/arc3/render_authored_frames.py`.

**Spoilers.** The Description column says what each task is, which is the thing the play
surface exists to make people work out for themselves. Do not hand this page to anyone you
want a blind first play from.

{"**" + str(unclassified) + " games are Unclassified** — add them to `server/data/arc3-games/categories.json`." if unclassified else ""}

| Game | Category | Grid | Levels | Description | Preview | Actions |
|------|----------|------|--------|-------------|---------|---------|
""" + "\n".join(rows) + "\n"

    if args.check:
        if not OUT.exists() or OUT.read_text() != body:
            print(f"STALE: {OUT.relative_to(REPO)} does not match the data. Re-run this script.", file=sys.stderr)
            return 1
        print("registry is current")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(REPO)}: {len(rows)} games, {unclassified} unclassified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
