"""
Author: Claude Opus 5
Date: 2026-09-18
PURPOSE: Turn one official ARC-AGI-3 config's public-set runs (cached by
         pull_official_public_runs.py) into a readable Markdown digest: for every game where
         the model cleared at least one level, and for every level it cleared, the note it
         wrote on the move that cleared the level. Models that carry notes forward (Claude
         Opus 5 writes a "Context notes (carry forward)" block every move) put their whole
         working model of the level into that note -- controls, goal, progress, and what
         they expect the move to do -- so the clearing note is the best single summary of
         how it solved the level. The full move-by-move text stays in
         data/arc3-official-runs/levels-won.jsonl.gz.

         Usage:
             python scripts/arc3/digest_official_reasoning.py anthropic-claude-opus-5-high
         Writes docs/arc3-official-runs/<config>-level-clears.md
SRP/DRY check: Pass -- formatting only; reads the per-run cache written by
         pull_official_public_runs.py and changes nothing there.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
CACHE_DIR = REPO / "data" / "arc3-official-runs" / "cache"
OUT_DIR = REPO / "docs" / "arc3-official-runs"


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: digest_official_reasoning.py <config>, e.g. anthropic-claude-opus-5-high", file=sys.stderr)
        return 2
    config = sys.argv[1]
    runs = []
    for path in CACHE_DIR.glob("*.json"):
        run = json.loads(path.read_text(encoding="utf-8"))
        if run.get("config") == config:
            runs.append(run)
    if not runs:
        print(f"no cached runs for {config}; run pull_official_public_runs.py first", file=sys.stderr)
        return 1
    runs.sort(key=lambda r: (-(r.get("levelsCompleted") or 0), r["gameId"]))
    progressed = [r for r in runs if (r.get("levelsCompleted") or 0) > 0]
    cleared_total = sum(r.get("levelsCompleted") or 0 for r in runs)
    level_total = sum(r.get("levelCount") or 0 for r in runs)

    lines = [
        f"<!-- Generated by scripts/arc3/digest_official_reasoning.py from ARC Prize's public-set runs "
        f"({config}). Do not edit by hand; re-run the script. -->",
        "",
        f"# {config}: how it cleared each level",
        "",
        f"ARC Prize's own run of `{config}` on the 25 public ARC-AGI-3 games. "
        f"Won {sum(r['state'] == 'WIN' for r in runs)} of {len(runs)} games and cleared {cleared_total} of "
        f"{level_total} levels, with at least one level on {len(progressed)} games.",
        "",
        "For each level it cleared: the moves it took, ARC's human baseline, and the note it wrote on the "
        "move that cleared the level. Full move-by-move text for every cleared level is in "
        "`data/arc3-official-runs/levels-won.jsonl.gz`.",
        "",
        "| Game | Result | Levels | Moves |",
        "| --- | --- | --- | --- |",
    ]
    for run in runs:
        lines.append(f"| {run['gameId']} | {run['state']} | {run.get('levelsCompleted')}/{run.get('levelCount')} | {run['moves']} |")
    for run in progressed:
        lines += ["", "---", "", f"## {run['gameId']}: {run['state']}, {run.get('levelsCompleted')}/{run.get('levelCount')} levels",
                  "", f"Replay: https://arcprize.org/replay/{run['guid']}"]
        baselines = run.get("levelBaselineActions") or []
        for level in run["levels"]:
            if not level["cleared"]:
                continue
            index = level["level"] - 1
            baseline = baselines[index] if index < len(baselines) else "?"
            clearing = next((s["note"] for s in reversed(level["steps"]) if s["note"]), None)
            lines += ["", f"### Level {level['level']}: {level['moves']} moves (human baseline {baseline})", ""]
            if clearing:
                lines += ["```text", clearing.strip(), "```"]
            else:
                lines.append("_No note on this level._")
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out = OUT_DIR / f"{config}-level-clears.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[digest_official_reasoning] wrote {out.relative_to(REPO)} ({out.stat().st_size / 1e3:.0f} KB, "
          f"{cleared_total} cleared levels on {len(progressed)} games)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
