/*
Author: Claude Opus 5
Date: 2026-08-30
PURPOSE: The blind task grid — arc3.markbarney.net's play surface. Every tile is one
         ARC-AGI-3 task, shown as its own opening frame and nothing else.

         2026-08-30 rewrite: the catalog now comes from /api/arc3-mirror/games, which
         mirrors arc3.sonpham.net (the source of truth for the synthetic programme) and
         strips every mechanic-naming field upstream of this component. The page it
         replaces read a DB-backed community catalog that had drifted months stale — 66
         rows covering ~40 games, against 300 upstream, with 13 duplicate rows for one
         game and a "ARC Prize Foundation — 3 tasks" section over 3 of 25.

         NO-SPOILER RULE. A player is meant to infer the rules, the controls and the goal
         from the frame; anything that names the mechanic turns their run into worthless
         baseline data. This page therefore renders no title, no description and no tags.
         The previous version passed `title={game.displayName}` as a hover tooltip, which
         handed "Light Bender" to anyone who rested a cursor on a tile — that is removed
         and must not come back. Category headings ("Official", "Community") stay: they
         name provenance, not play.

         The frame itself is safe and is the point: it is exactly what a player sees on
         starting, rendered server-side from a single RESET.
SRP/DRY check: Pass — presentation only; fetching/stripping lives in Arc3MirrorCatalog,
         and this reuses Arc3PixelPage + SpriteMosaic rather than adding new primitives.
*/

import { useMemo, useState } from 'react';
import { useLocation } from 'wouter';
import { useQuery } from '@tanstack/react-query';
import { Search } from 'lucide-react';
import { Arc3PixelPage, SpriteMosaic } from '@/components/arc3-community/Arc3PixelUI';

/** Mirrors MirroredGame in server/services/arc3Mirror/Arc3MirrorCatalog.ts. */
interface MirroredGame {
  gameId: string;
  className: string;
  /** Upstream's own slug, open by design -- see SECTION_LABELS. */
  category: string;
  official: boolean;
  defaultFps: number;
  tileScale: number;
}

interface GamesResponse {
  success: boolean;
  data: { games: MirroredGame[]; total: number };
}

/** One row of the review queue, already in the order it should be played. */
interface ReviewEntry {
  gameId: string;
}

interface ReviewResponse {
  success: boolean;
  data: { games: ReviewEntry[] };
}

/* Official ARC-AGI-3 task-page palette (measured from arcprize.org computed styles). */
const ARC = {
  ground: '#0E0C0C',
  text: '#E3E1DF',
  dim: '#9A9694',
  faint: '#6E6A68',
  cell: '#191919',
  cellBorder: '#262626',
  pink: '#E53AA3',
  pinkAlt: '#C42F89',
  control: '#393736',
};

/**
 * Section order and copy. Headings name where a task came from, never what it does --
 * upstream's own category slugs leak nothing, but "redbluepill" is a repo name rather
 * than English and "ai-generated" undersells what it is.
 *
 * ORDER MATTERS: the tasks coming off our own generation pipeline lead. The official 25
 * are the famous ones but they are not what this programme is producing, and burying our
 * output beneath them made the page read as a mirror of arcprize.org.
 */
const SECTION_LABELS: { key: string; label: string; note: string }[] = [
  { key: 'ai-generated', label: 'Fresh off the pipeline', note: 'Generated by our agent, newest first. This is the set we need judged — near-copies and ones that fall over to random mashing are held back.' },
  { key: 'custom', label: 'Built in-house', note: 'Hand-made by us and by Son Pham.' },
  { key: 'redbluepill', label: 'Community catalog', note: 'Contributed tasks.' },
  { key: 'official', label: 'ARC Prize Foundation', note: 'The official ARC-AGI-3 set.' },
];

/**
 * Any category upstream invents that is not in the list above still renders, under its
 * own slug, after the known ones. `ai-generated` arrived with 571 games the day after
 * this page shipped and a hardcoded list dropped every one of them silently -- the page
 * said "1-60 of 877" while rendering nothing for them. Never again: unknown is a
 * labelling gap, not a reason to hide a task.
 */
function sectionsFor(games: MirroredGame[]): { key: string; label: string; note: string }[] {
  const known = new Set(SECTION_LABELS.map((s) => s.key));
  const extras = [...new Set(games.map((g) => g.category))]
    .filter((c) => !known.has(c))
    .sort()
    .map((c) => ({ key: c, label: c, note: '' }));
  return [...SECTION_LABELS, ...extras];
}

const PAGE_SIZE = 60;

/** Stable per-game seed so a task's fallback sprite never changes between visits. */
function seedFor(gameId: string): number {
  let hash = 2166136261;
  for (let i = 0; i < gameId.length; i++) {
    hash ^= gameId.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

function TaskCell({ game, index, onPlay }: {
  game: MirroredGame;
  index: number;
  onPlay: () => void;
}) {
  const [broken, setBroken] = useState(false);
  return (
    <button
      onClick={onPlay}
      className="group block text-left w-full"
      /* No `title` attribute. A tooltip is a spoiler surface like any other. */
      aria-label={`Play task ${game.gameId}`}
    >
      <div
        className="relative aspect-square overflow-hidden transition-colors"
        style={{ background: ARC.cell, border: `1px solid ${ARC.cellBorder}` }}
      >
        {/* The task's own opening frame, rendered server-side from a single RESET. If
            rendering fails the deterministic sprite stands in so the grid never holes. */}
        {broken ? (
          <SpriteMosaic
            seed={seedFor(game.gameId)}
            width={8}
            height={8}
            className="!border-0 !shadow-none w-full h-full opacity-40"
          />
        ) : (
          <img
            src={`/api/arc3-mirror/games/${encodeURIComponent(game.gameId)}/thumbnail?size=256`}
            alt=""
            loading="lazy"
            decoding="async"
            onError={() => setBroken(true)}
            className="w-full h-full opacity-90 group-hover:opacity-100 transition-opacity"
            /* Pixel grids must not be smoothed. */
            style={{ imageRendering: 'pixelated', display: 'block' }}
          />
        )}
        {/* CRT scanlines, matching the official task screen treatment. */}
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            backgroundImage:
              'repeating-linear-gradient(0deg, rgba(0,0,0,0) 0 2px, rgba(0,0,0,.38) 2px 4px)',
          }}
        />
      </div>
      <div
        className="flex items-center px-2 py-1"
        style={{ background: index % 2 === 0 ? ARC.pink : ARC.pinkAlt }}
      >
        <span className="text-[11px] tracking-[.55px] text-white truncate">
          {game.gameId}
        </span>
      </div>
    </button>
  );
}

export default function CommunityGallery() {
  const [, setLocation] = useLocation();
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(0);
  // With the pipeline set leading and 877 tasks paginated 60 at a time, the official 25
  // would otherwise sit ten pages deep. These keep every section one click away.
  const [category, setCategory] = useState<string | null>(null);

  const { data, isLoading, isError } = useQuery<GamesResponse>({
    queryKey: ['/api/arc3-mirror/games'],
    // The catalog is one upstream fetch behind a 5-minute server cache; re-fetching it
    // on every window focus buys nothing and costs a round trip on a page that is mostly
    // images.
    staleTime: 5 * 60 * 1000,
  });

  /**
   * The review queue, in play order. Not `?all=1`: the ORDER is the server's to decide
   * (Arc3Triage), and re-deriving it here is how this page and "Next task" would drift
   * apart. Static behind a one-hour cache; a failure costs the ordering and nothing else.
   */
  const { data: review } = useQuery<ReviewResponse>({
    queryKey: ['/api/arc3-mirror/review-queue'],
    staleTime: 60 * 60 * 1000,
  });

  const games = useMemo(() => data?.data?.games ?? [], [data]);

  /**
   * gameId -> its place in the review queue, which is newest generated work first.
   *
   * This page used to show the pipeline set in whatever order the manifest listed, so a
   * visitor's first tile was an arbitrary task — while "Next task" was already walking
   * the queue. Same set, two different orders, and the one people actually landed on was
   * the meaningless one.
   *
   * A task with no place in the queue (culled as a duplicate or as random-mashable, or
   * from a batch nobody has probed yet) sorts after the queued ones rather than
   * disappearing: a cull you cannot see is a cull nobody can overrule.
   */
  const queuePlace = useMemo(() => {
    const m = new Map<string, number>();
    (review?.data?.games ?? []).forEach((g, i) => m.set(g.gameId, i));
    return m;
  }, [review]);

  /** Pipeline output leads, newest first within it; `null` means every category. */
  const ordered = useMemo(() => {
    const section = new Map(sectionsFor(games).map((s, i) => [s.key, i]));
    return [...games].sort((a, b) => {
      const bySection = (section.get(a.category) ?? 99) - (section.get(b.category) ?? 99);
      if (bySection !== 0) return bySection;
      // Sources other than our pipeline have no verdicts, so they all tie here and keep
      // manifest order — which is right, since none of them is what we need judged.
      return (queuePlace.get(a.gameId) ?? Infinity) - (queuePlace.get(b.gameId) ?? Infinity);
    });
  }, [games, queuePlace]);

  /* Search matches the id only. There is nothing else to match on, by design. */
  const filtered = useMemo(() => {
    const byCategory = category ? ordered.filter((g) => g.category === category) : ordered;
    const q = search.trim().toLowerCase();
    if (!q) return byCategory;
    return byCategory.filter((g) => g.gameId.toLowerCase().includes(q));
  }, [ordered, search, category]);

  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const safePage = Math.min(page, pageCount - 1);
  const visible = filtered.slice(safePage * PAGE_SIZE, (safePage + 1) * PAGE_SIZE);

  // Counts come from `filtered`, not `visible`. Sectioning the current page and then
  // counting it reports "how many of this category landed on page 1" -- which is how the
  // old page came to announce "ARC Prize Foundation - 3 tasks" over a set of 25.
  const sections = sectionsFor(games)
    .map((s) => ({
      ...s,
      games: visible.filter((g) => g.category === s.key),
      total: filtered.filter((g) => g.category === s.key).length,
    }))
    .filter((s) => s.games.length > 0);

  return (
    <Arc3PixelPage vars={{ '--arc3-bg': ARC.ground }}>
      <div className="max-w-[1100px] mx-auto px-4 py-8">
        <header className="mb-8">
          <h1 className="text-[13px] tracking-[3px] uppercase mb-2" style={{ color: ARC.text }}>
            ARC-AGI-3 tasks
          </h1>
          <p className="text-[13px] leading-relaxed max-w-[64ch]" style={{ color: ARC.dim }}>
            Pick one and work out what it does. You are not told the rules, the controls or
            the goal — that is the experiment. Nothing here is timed and there is no score
            to beat.
          </p>
        </header>

        <div className="flex items-center gap-2 mb-8 max-w-[360px]">
          <div className="relative flex-1">
            <Search
              className="absolute left-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5"
              style={{ color: ARC.faint }}
            />
            <input
              value={search}
              onChange={(e) => { setSearch(e.target.value); setPage(0); }}
              placeholder="Filter by task id…"
              className="w-full bg-transparent pl-7 pr-2 py-1.5 text-[12px] outline-none"
              style={{ border: `1px solid ${ARC.control}`, color: ARC.text }}
            />
          </div>
          <span className="text-[11px] shrink-0" style={{ color: ARC.faint }}>
            {filtered.length}
          </span>
        </div>

        {/* Jump straight to a section. Without these the official 25 sit ten pages behind
            the pipeline set, which is the right lead but the wrong way to hide them. */}
        <div className="flex flex-wrap gap-2 mb-8">
          {[{ key: null as string | null, label: 'All', count: games.length }].concat(
            sectionsFor(games)
              .map((sec) => ({
                key: sec.key as string | null,
                label: sec.label,
                count: games.filter((g) => g.category === sec.key).length,
              }))
              .filter((sec) => sec.count > 0),
          ).map((chip) => {
            const active = category === chip.key;
            return (
              <button
                key={chip.label}
                onClick={() => { setCategory(chip.key); setPage(0); }}
                className="text-[11px] px-2.5 py-1 transition-colors"
                style={{
                  border: `1px solid ${active ? ARC.pink : ARC.control}`,
                  background: active ? ARC.pink : 'transparent',
                  color: active ? '#fff' : ARC.dim,
                }}
              >
                {chip.label} <span style={{ opacity: 0.7 }}>{chip.count}</span>
              </button>
            );
          })}
        </div>

        {isLoading && (
          <p className="text-[12px]" style={{ color: ARC.faint }}>Loading tasks…</p>
        )}

        {isError && (
          <p className="text-[12px]" style={{ color: ARC.pink }}>
            The task catalog is unreachable right now. Try again in a moment.
          </p>
        )}

        {!isLoading && !isError && filtered.length === 0 && (
          <p className="text-[12px]" style={{ color: ARC.faint }}>No task ids match that filter.</p>
        )}

        {sections.map((section) => (
          <section key={section.key} className="mb-10">
            <div className="flex items-baseline gap-3 mb-1">
              <h2 className="text-[12px] tracking-[2px] uppercase" style={{ color: ARC.text }}>
                {section.label}
              </h2>
              <span className="text-[11px]" style={{ color: ARC.faint }}>
                {section.games.length < section.total
                  ? `${section.games.length} of ${section.total}`
                  : section.total}
              </span>
            </div>
            <p className="text-[11px] mb-3" style={{ color: ARC.faint }}>{section.note}</p>
            <div className="grid gap-3 grid-cols-[repeat(auto-fill,minmax(112px,1fr))]">
              {section.games.map((game, i) => (
                <TaskCell
                  key={game.gameId}
                  game={game}
                  index={i}
                  onPlay={() => setLocation(`/arc3/play/${game.gameId}`)}
                />
              ))}
            </div>
          </section>
        ))}

        {pageCount > 1 && (
          <div className="flex items-center gap-4 text-[11px]" style={{ color: ARC.dim }}>
            <button
              disabled={safePage === 0}
              onClick={() => setPage((p) => Math.max(0, p - 1))}
              className="disabled:opacity-30 px-2 py-1"
              style={{ border: `1px solid ${ARC.control}` }}
            >
              ‹ Prev
            </button>
            <span>
              {safePage * PAGE_SIZE + 1}–{Math.min((safePage + 1) * PAGE_SIZE, filtered.length)} of {filtered.length}
            </span>
            <button
              disabled={safePage >= pageCount - 1}
              onClick={() => setPage((p) => Math.min(pageCount - 1, p + 1))}
              className="disabled:opacity-30 px-2 py-1"
              style={{ border: `1px solid ${ARC.control}` }}
            >
              Next ›
            </button>
          </div>
        )}

        <footer className="mt-12 pt-6 text-[11px]" style={{ borderTop: `1px solid ${ARC.cellBorder}`, color: ARC.faint }}>
          Tasks mirrored from{' '}
          <a href="https://arc3.sonpham.net" className="underline" style={{ color: ARC.dim }}>
            arc3.sonpham.net
          </a>
          , the source of truth for the synthetic ARC-AGI-3 programme.
        </footer>
      </div>
    </Arc3PixelPage>
  );
}
