/**
 * Author: GPT-6 Sol / Codex
 * Date: 2026-10-09
 * PURPOSE: Public reporting-method copy shared by the newspaper page and crawler HTML.
 *          09-Oct-2026 (Claude Opus 5.5): says where each person's picture comes from. Later the same
 *          day: early and late editions, the GPT-6 Luna wire and the live tables.
 * SRP/DRY check: Pass — keeps the disclosure in one place; operational details stay in docs/newsroom.
 */
export const NEWS_METHOD = [
  { heading: 'Spare compute, busy sports desk', text: 'When we’re not Kaggling, a little spare compute takes a turn at the sports desk. The ARC Daily Digest follows the contestants, contenders and research around ARC Prize, with VoynichLabs sponsoring the publication.' },
  { heading: 'AI drafts, recorded evidence', text: 'GPT-6 Sol writes the editions and GPT-6 Luna writes the short wire stories, both from dated public leaderboard observations and linked primary sources. Reporting helpers check the article format, cited sources and box-score figures; every figure in a wire story is checked automatically against its saved brief before it is published. The reporting run also checks narrative numbers, comparisons and identities against its evidence before publication. AI illustrations are labeled as editorial artwork.' },
  { heading: 'Two contests, two editions', text: 'The early edition comes out at 6 am and the late edition at 6 pm Eastern, and each is posted to X. ARC-AGI-2 and ARC-AGI-3 remain separate competitions. The early comparison starts at UTC midnight; the late comparison uses the prior calendar day’s 6 pm Eastern observation. Missing history stays unknown. Each edition links its exact saved observations, and public standings and medal bands remain provisional.' },
  { heading: 'The live tables and the wire', text: 'The ticker, standings, movers and past-winners tables on the front page are drawn from the public boards the paper saves every half hour. Changes compare with the save about a day earlier; a team’s earlier rank or score is shown only when the saved history supports it, and is left blank otherwise. Through the day the wire desk files short stories on the moves, each with its saved evidence. If a scheduled run fails, a backup desk (Claude Haiku 5.5) covers it under the same rules, and those stories say so.' },
  { heading: 'News between the editions', text: 'A six-hour research desk gathers public posts, threads and linked releases. Significant developments can receive a separate dated dispatch between editions. Articles link the original posts and distinguish a contestant’s claim from an established result. The personal briefing can include subscriber posts; public coverage uses public sources.' },
  { heading: 'Teams on the board, people in the story', text: 'Team IDs belong to their competition. Verified people have separate records connecting their dated roster observations, public accounts and relevant Hall of Fame cards. Each person’s picture is either their own illustrated ARC Explainer Hall of Fame card or the profile picture on their verified Kaggle account; people without one appear as initials. An observed membership does not establish a joining date, team leadership or credit for a particular submission. Historical achievements retain their original year.' },
  { heading: 'Corrections and sponsorship', text: 'Published editions keep their original evidence. Later reporting and identified corrections add context as the race develops. VoynichLabs placements are labeled advertisements. Send a specific source link or correction through ARC Explainer’s feedback page.' },
];
