/**
 * Author: Cascade using Claude Sonnet 4 (2025-10-12)
 * Date: 2025-10-12
 * PURPOSE: jjosh ARC AGI solver service - integrates external Python solver via git submodule
 * with JSON contract interface. Executes Python CLI and parses JSON output for ARC puzzle solving.
 *
 * Integration Pattern:
 * - Calls python solvers/arc_agi/arc_agi/cli.py --task <path/to/task.json>
 * - Expects JSON response: { "program": "<name>", "predicted_output_grid": [[...]] }
 * - Handles both single and multiple prediction formats
 * - SRP/DRY check: Pass - Single responsibility (external solver integration)
 */

import { ARCTask } from "../../shared/types.js";
import { BaseAIService, ServiceOptions, TokenUsage, AIResponse, PromptPreview, ModelInfo } from "./base/BaseAIService.js";
import type { PromptOptions } from "./promptBuilder.js";
import { spawn } from 'child_process';
import path from 'path';
import fs from 'fs/promises';

export class JjoshService extends BaseAIService {
  protected provider = "jjosh";
  protected models: Record<string, string> = {
    "jjosh-arc-agi": "arc-agi"
  };

  /**
   * Execute external jjosh ARC AGI solver
   */
  async analyzePuzzleWithModel(
    task: ARCTask,
    modelKey: string,
    taskId: string,
    temperature: number = 0.2,
    promptId?: string,
    customPrompt?: string,
    options?: PromptOptions,
    serviceOpts?: ServiceOptions
  ): Promise<AIResponse> {
    const startTime = Date.now();

    try {
      // Write task to temporary file for Python CLI
      const tempTaskPath = await this.writeTaskToTempFile(task, taskId);

      // Execute Python solver
      const result = await this.executePythonSolver(tempTaskPath);

      // Clean up temp file
      await fs.unlink(tempTaskPath).catch(() => {}); // Ignore cleanup errors

      // Parse and validate result
      const parsedResult = JSON.parse(result);

      if (parsedResult.error) {
        throw new Error(`Python solver error: ${parsedResult.error}`);
      }

      // Build response in expected format
      const response: AIResponse = {
        model: modelKey,
        taskId,
        confidence: 75, // Default confidence for external solver
        patternDescription: `External solver program: ${parsedResult.program}`,
        solvingStrategy: `Executed external ARC AGI solver program: ${parsedResult.program}`,
        hints: [
          "External solver provided solution",
          `Program type: ${parsedResult.program}`,
          "Solution generated by jjosh/arc_agi solver"
        ],
        temperature,
        apiProcessingTimeMs: Date.now() - startTime,
        reasoningLog: `External solver executed successfully. Program: ${parsedResult.program}`,
        hasReasoningLog: true,
        providerRawResponse: JSON.stringify(parsedResult)
      };

      // Handle both single and multiple prediction formats
      if (parsedResult.multiple_predicted_outputs) {
        response.multiplePredictedOutputs = parsedResult.multiple_predicted_outputs;
        response.hasMultiplePredictions = true;
        response.predictedOutputGrid = parsedResult.multiple_predicted_outputs[0]; // For backward compatibility
      } else {
        response.predictedOutputGrid = parsedResult.predicted_output_grid;
        response.hasMultiplePredictions = false;
      }

      return response;

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      logger.error(`[jjosh-service] Error analyzing puzzle ${taskId}: ${errorMessage}`);

      throw new Error(`jjosh solver failed: ${errorMessage}`);
    }
  }

  /**
   * Write ARC task to temporary JSON file for Python CLI
   */
  private async writeTaskToTempFile(task: ARCTask, taskId: string): Promise<string> {
    const tempDir = path.join(process.cwd(), 'temp');
    await fs.mkdir(tempDir, { recursive: true });

    const tempPath = path.join(tempDir, `task-${taskId}-${Date.now()}.json`);
    await fs.writeFile(tempPath, JSON.stringify(task, null, 2));

    return tempPath;
  }

  /**
   * Execute Python solver CLI and capture JSON output
   */
  private async executePythonSolver(taskPath: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const pythonBin = process.platform === 'win32' ? 'python' : 'python3';
      const cliPath = path.join(process.cwd(), 'solvers', 'arc_agi', 'arc_agi', 'cli.py');

      const child = spawn(pythonBin, ['--task', taskPath], {
        cwd: path.dirname(cliPath),
        stdio: ['pipe', 'pipe', 'pipe']
      });

      let stdout = '';
      let stderr = '';

      child.stdout.on('data', (data) => {
        stdout += data.toString();
      });

      child.stderr.on('data', (data) => {
        stderr += data.toString();
      });

      child.on('close', (code) => {
        if (code !== 0) {
          reject(new Error(`Python solver exited with code ${code}: ${stderr}`));
        } else {
          resolve(stdout.trim());
        }
      });

      child.on('error', (error) => {
        reject(new Error(`Failed to start Python solver: ${error.message}`));
      });
    });
  }

  /**
   * Preview prompt (not applicable for external solver)
   */
  async generatePromptPreview(
    task: ARCTask,
    modelKey: string,
    promptId?: string,
    customPrompt?: string,
    options?: PromptOptions,
    serviceOpts?: ServiceOptions
  ): Promise<PromptPreview> {
    return {
      systemPrompt: "External ARC AGI solver - no prompt preview available",
      userPrompt: "External solver executes Python CLI directly",
      model: modelKey,
      temperature: 0.2,
      estimatedTokens: 0,
      estimatedCost: 0
    };
  }

  /**
   * Get model information
   */
  getModelInfo(modelKey: string): ModelInfo {
    return {
      name: "jjosh-arc-agi",
      provider: "jjosh",
      type: "external-solver",
      description: "External ARC AGI solver from jjoshua2/arc_agi repository"
    };
  }

  /**
   * Streaming not supported for external solver
   */
  async analyzePuzzleWithStreaming(
    task: ARCTask,
    modelKey: string,
    taskId: string,
    temperature: number = 0.2,
    promptId?: string,
    customPrompt?: string,
    options?: PromptOptions,
    serviceOpts?: ServiceOptions
  ): Promise<AIResponse> {
    throw new Error("Streaming not supported for external jjosh solver");
  }
}

export const jjoshService = new JjoshService();
