name: bump-arc_agi
on:
  repository_dispatch:
    types: [arc_agi_released]
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.EXPLAINER_PAT }}
          submodules: true
      - run: |
          git submodule update --remote solvers/arc_agi
          git add solvers/arc_agi
          git -c user.name="bot" -c user.email="bot@users.noreply.github.com" \
            commit -m "chore(submodule): bump arc_agi to ${{ github.event.client_payload.tag }}" || exit 0
          git push
