name: solver-smoke

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install numpy
      - run: python solvers/arc_agi/arc_agi/cli.py --task data/arc-heavy/task_0.json
